# Generated by Django 4.1.3 on 2022-11-29 21:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BoardGame',
            fields=[
                ('idBoardGame', models.IntegerField(primary_key=True, serialize=False)),
                ('titulo', models.CharField(max_length=60)),
                ('precio', models.FloatField()),
                ('complejidad', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Film',
            fields=[
                ('idFilm', models.IntegerField(primary_key=True, serialize=False)),
                ('titulo', models.CharField(max_length=60)),
                ('director', models.CharField(max_length=60)),
                ('sinopsis', models.TextField()),
                ('fecha_estreno', models.DateField()),
                ('pais', models.CharField(max_length=20)),
            ],
        ),
    ]
