# Generated by Django 4.1.3 on 2022-12-27 13:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_remove_film_sinopsis'),
    ]

    operations = [
        migrations.AddField(
            model_name='boardgame',
            name='descripcion',
            field=models.TextField(default=''),
        ),
    ]
