# Generated by Django 4.1.3 on 2023-01-02 13:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_boardgame_descripcion'),
    ]

    operations = [
        migrations.AddField(
            model_name='film',
            name='genero',
            field=models.CharField(default='Sin genero', max_length=50),
        ),
        migrations.AddField(
            model_name='film',
            name='sinopsis',
            field=models.TextField(default='null'),
        ),
    ]
