# Generated by Django 4.1.3 on 2022-11-14 09:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=255)),
                ('email', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Receta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=255)),
                ('ingredientes', models.CharField(max_length=255)),
                ('preparacion', models.CharField(max_length=255)),
                ('imagen', models.CharField(max_length=255)),
                ('fecha_registro', models.CharField(max_length=255)),
                ('usuario_autor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='practica1.usuario')),
            ],
        ),
        migrations.CreateModel(
            name='Comentario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('texto', models.CharField(max_length=255)),
                ('receta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='practica1.receta')),
            ],
        ),
    ]
